<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_tdpKsDsGEfCUCLU1D69YIQ" name="Avaliação de fornecedor estratégico" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_tdpKsTsGEfCUCLU1D69YIQ" name="Avaliação de fornecedor estratégico">
      <elements xmi:type="process:StartEvent" xmi:id="_tdpKszsGEfCUCLU1D69YIQ" documentation="Evento de início do processo de qualificação e avaliação de fornecedores. Este evento é disparado quando um utilizador inicia um novo pedido de avaliação.&#xD;&#xA;" name="Início" outgoing="_G-gq8DsJEfCUCLU1D69YIQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_tdpKtDsGEfCUCLU1D69YIQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_tdpKtTsGEfCUCLU1D69YIQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_tdpKtjsGEfCUCLU1D69YIQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_LEiO8EuNEfCyX9uolcYbeQ" documentation="Decide se o fornecedor é estratégico. Se sim, segue para o fluxo estratégico; se não, segue para o fluxo normal.&#xD;&#xA;&#xD;&#xA;" name="Tipo de fornecedor estratégico?" outgoing="_g9TKUEzzEfC0mryHjxjYFA _o7MN80zzEfC0mryHjxjYFA" incoming="_G-gq8DsJEfCUCLU1D69YIQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_GsoQwjsJEfCUCLU1D69YIQ" name="Auditoria e Avaliação de Fornecedor" content="Auditoria e Avaliação de Fornecedor" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_GsoQwTsJEfCUCLU1D69YIQ" name="dynamicDescription()" content="'Realize a auditoria e preencha o questionário de avaliação do fornecedor, verificando todos os critérios necessários.'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_GsoQwzsJEfCUCLU1D69YIQ" name="descriptionAfterCompletion()" content="'A auditoria e o questionário de avaliação foram concluídos. Todas as evidências e observações foram registradas.'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_NEm2sEz1EfCtoJWwOFxQ4w" name="Avaliar níveis de serviço estabelecido" outgoing="_GUKPEE0gEfCJQ8HsncGeQQ" incoming="_g9TKUEzzEfC0mryHjxjYFA" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_g9R8MUzzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_g9R8MEzzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_g9R8MkzzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_SWHFYE0dEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_SWHFYU0dEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TFmooE0dEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_SWHFYk0dEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.nivelServico = avaliacaoFornecedorInput.nivelServico&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_6Yv34E0dEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_SWHFY00dEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_g9R8M0zzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_g9R8NEzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_g9R8NUzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_g9R8N0zzEfC0mryHjxjYFA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_g9R8NkzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_NEqhGUz1EfCtoJWwOFxQ4w">
          <targetForm xmi:type="expression:Expression" xmi:id="_FRiREEz3EfCtoJWwOFxQ4w" name="newForm8" content="84097145-c3da-408f-bbea-fa4f79b411a3" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_NEqhGEz1EfCtoJWwOFxQ4w">
          <inputs xmi:type="process:ContractInput" xmi:id="_w228oEz2EfCtoJWwOFxQ4w" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_w228oUz2EfCtoJWwOFxQ4w" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228okz2EfCtoJWwOFxQ4w" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228o0z2EfCtoJWwOFxQ4w" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228pEz2EfCtoJWwOFxQ4w" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228pUz2EfCtoJWwOFxQ4w" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228pkz2EfCtoJWwOFxQ4w" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228p0z2EfCtoJWwOFxQ4w" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228qEz2EfCtoJWwOFxQ4w" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228qUz2EfCtoJWwOFxQ4w" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228qkz2EfCtoJWwOFxQ4w" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228q0z2EfCtoJWwOFxQ4w" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228rEz2EfCtoJWwOFxQ4w" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_w228rUz2EfCtoJWwOFxQ4w" name="numeroIncidentes" type="INTEGER" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24KwEz2EfCtoJWwOFxQ4w" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24KwUz2EfCtoJWwOFxQ4w" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24Kwkz2EfCtoJWwOFxQ4w" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24Kw0z2EfCtoJWwOFxQ4w" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24KxEz2EfCtoJWwOFxQ4w" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_w24KxUz2EfCtoJWwOFxQ4w" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_NEqhG0z1EfCtoJWwOFxQ4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_w14lEE0eEfCJQ8HsncGeQQ" name="Avaliar não conformidade na entrega" outgoing="_bKgWY00hEfCJQ8HsncGeQQ" incoming="_o7MN80zzEfC0mryHjxjYFA" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_o7Lm4kzzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_o7Lm4UzzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_o7Lm40zzEfC0mryHjxjYFA" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_1sHewE0fEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_1sHewU0fEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2zVlgE0fEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_1sHewk0fEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.naoConformidades = avaliacaoFornecedorInput.naoConformidades&#xD;&#xA;avaliacao.descricaoNaoConformidades = avaliacaoFornecedorInput.descricaoNaoConformidades&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_41UEUE0fEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_1sHew00fEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_o7Lm5EzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_o7Lm5UzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_o7Lm5kzzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_o7Lm6EzzEfC0mryHjxjYFA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_o7Lm50zzEfC0mryHjxjYFA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_w18PeU0eEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_JHvmcE0fEfCJQ8HsncGeQQ" name="newForm9" content="2792dabb-cd0f-43b2-bb45-f19cc30080f3" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_w18PeE0eEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_IZeyQE0fEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyQU0fEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyQk0fEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyQ00fEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyRE0fEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyRU0fEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyRk0fEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyR00fEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeySE0fEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeySU0fEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeySk0fEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyS00fEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyTE0fEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_IZeyTU0fEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyTk0fEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyT00fEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyUE0fEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyUU0fEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyUk0fEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_IZeyU00fEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_w18Pe00eEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_GtG6kE0gEfCJQ8HsncGeQQ" name="Avaliar gestão de incidentes" outgoing="_ZVRdo00iEfCJQ8HsncGeQQ" incoming="_GUKPEE0gEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_GUF9ok0gEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_GUF9oU0gEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_GUF9o00gEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_JbEgME0hEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_JbEgMU0hEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JvOyUE0hEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_JbEgMk0hEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.avaliacaoIncidentes = avaliacaoFornecedorInput.avaliacaoIncidentes&#xD;&#xA;avaliacao.numeroIncidentes = avaliacaoFornecedorInput.numeroIncidentes&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_LT1_sE0hEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_JbEgM00hEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_GUF9pE0gEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_GUF9pU0gEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GUF9pk0gEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_GUF9qE0gEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_GUF9p00gEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_GtG6mk0gEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_TSyosE0gEfCJQ8HsncGeQQ" name="newForm10" content="a39dce4b-f7a2-4fe8-948b-8a295c1234ea" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_GtG6mU0gEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_R1-scE0gEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-scU0gEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sck0gEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sc00gEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sdE0gEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sdU0gEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sdk0gEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sd00gEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-seE0gEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-seU0gEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sek0gEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-se00gEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sfE0gEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_R1-sfU0gEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sfk0gEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sf00gEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sgE0gEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sgU0gEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sgk0gEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_R1-sg00gEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_GtG6nE0gEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_bXGA4E0hEfCJQ8HsncGeQQ" name="Avaliar condições de crédito" outgoing="_NUi2sE0iEfCJQ8HsncGeQQ" incoming="_bKgWY00hEfCJQ8HsncGeQQ" actor="_oyfOUEvJEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_bKfvUk0hEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_bKfvUU0hEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_bKfvU00hEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="__Y9soE0hEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="__Y9soU0hEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_AIJt4E0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="__Y9sok0hEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.condicoesCredito = avaliacaoFornecedorInput.condicoesCredito&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_BRU8cE0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="__Y9so00hEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_bKfvVE0hEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_bKfvVU0hEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_bKfvVk0hEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_bKfvWE0hEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_bKfvV00hEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_bXGA6k0hEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_rwR10E0hEfCJQ8HsncGeQQ" name="newForm11" content="026430dc-7e9e-4451-8863-07ee7f14e930" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_bXGA6U0hEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_qrleoE0hEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleoU0hEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleok0hEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleo00hEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlepE0hEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlepU0hEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlepk0hEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlep00hEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleqE0hEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleqU0hEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleqk0hEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrleq00hEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlerE0hEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_qrlerU0hEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrlerk0hEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrler00hEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrlesE0hEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrlesU0hEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrlesk0hEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_qrles00hEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_bXGA7E0hEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_LVJx0E0iEfCJQ8HsncGeQQ" name="Avaliar gestão de incidente" outgoing="_QNLXEE0qEfCJQ8HsncGeQQ" incoming="_NUi2sE0iEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_LVJx0U0iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_LVJx0k0iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_LVJx000iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_LVJx1E0iEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_LVJx1U0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_LVJx1k0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_LVJx100iEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.avaliacaoIncidentes = avaliacaoFornecedorInput.avaliacaoIncidentes&#xD;&#xA;avaliacao.numeroIncidentes = avaliacaoFornecedorInput.numeroIncidentes&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_LVJx2E0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_LVJx2U0iEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_LVJx2k0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_LVJx200iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LVJx3E0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_LVJx3U0iEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_LVJx3k0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_LVJx300iEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_LVJx4E0iEfCJQ8HsncGeQQ" name="newForm10" content="a39dce4b-f7a2-4fe8-948b-8a295c1234ea" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_LVJx4U0iEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_LVJx4k0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx400iEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx5E0iEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx5U0iEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx5k0iEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx500iEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx6E0iEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx6U0iEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx6k0iEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx600iEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx7E0iEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx7U0iEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx7k0iEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LVJx700iEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx8E0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx8U0iEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx8k0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx800iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx9E0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LVJx9U0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_LVJx9k0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_ZjQ2UE0iEfCJQ8HsncGeQQ" name="Avaliar condições de formação e certificação" outgoing="_cqAvYE0jEfCJQ8HsncGeQQ" incoming="_ZVRdo00iEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZVQ2kk0iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZVQ2kU0iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ZVQ2k00iEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="__OLjgE0iEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="__OLjgU0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__jwx8E0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="__OLjgk0iEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.formacaoCertificacao = avaliacaoFornecedorInput.formacaoCertificacao&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_AFm6wE0jEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="__OMKkE0iEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ZVQ2lE0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ZVQ2lU0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZVQ2lk0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZVQ2mE0iEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ZVQ2l00iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_ZjQ2Wk0iEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_dVyswE0iEfCJQ8HsncGeQQ" name="newForm12" content="26c616de-d782-4fb3-b40d-17a6b14a890c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_ZjQ2WU0iEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_b84ZEE0iEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZEU0iEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZEk0iEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZE00iEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZFE0iEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZFU0iEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZFk0iEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZF00iEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZGE0iEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZGU0iEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZGk0iEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZG00iEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZHE0iEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_b84ZHU0iEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZHk0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZH00iEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZIE0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZIU0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZIk0iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_b84ZI00iEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_ZjQ2XE0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_c4Hc0E0jEfCJQ8HsncGeQQ" name="Avaliar não conformidades" outgoing="_45VkgE0mEfCJQ8HsncGeQQ" incoming="_cqAvYE0jEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_cqAIUk0jEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_cqAIUU0jEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_cqAIU00jEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_08n-sE0jEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_08n-sU0jEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1UVUEE0jEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_08n-sk0jEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.naoConformidades = avaliacaoFornecedorInput.naoConformidades&#xD;&#xA;avaliacao.descricaoNaoConformidades = avaliacaoFornecedorInput.descricaoNaoConformidades&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_3Sr3IE0jEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_08n-s00jEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_cqAIVE0jEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_cqAIVU0jEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cqAIVk0jEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_cqAIWE0jEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_cqAIV00jEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_c4Hc2k0jEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_iIApIE0jEfCJQ8HsncGeQQ" name="newForm13" content="20f0d6f1-18d4-4769-bbe8-5e07ab74f1f8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_c4Hc2U0jEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_gjhXkE0jEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXkU0jEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXkk0jEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXk00jEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXlE0jEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXlU0jEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXlk0jEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXl00jEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXmE0jEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXmU0jEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXmk0jEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXm00jEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXnE0jEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_gjhXnU0jEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXnk0jEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXn00jEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXoE0jEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXoU0jEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXok0jEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_gjhXo00jEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_c4Hc3E0jEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_5HxCEE0mEfCJQ8HsncGeQQ" name="Avaliar condições de fornecimento" outgoing="_Po5lVE0qEfCJQ8HsncGeQQ" incoming="_45VkgE0mEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_45U9cU0mEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_45U9cE0mEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_45U9ck0mEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_0V5ZEE0nEfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_0V5ZEU0nEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1CD7gE0nEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_0V5ZEk0nEfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAvaliacao&#xD;&#xA;avaliacao.condicoesFornecimento = avaliacaoFornecedorInput.condicoesFornecimento&#xD;&#xA;avaliacao.classificacaoDesempenho = avaliacaoFornecedorInput.classificacaoDesempenho&#xD;&#xA;avaliacao.responsavelAvaliacao = avaliacaoFornecedorInput.responsavelAvaliacao&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.observacoesAvaliacao&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_2YjNUE0nEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_0V5ZE00nEfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_45U9c00mEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_45U9dE0mEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_45U9dU0mEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_45U9d00mEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_45U9dk0mEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_5HxCGk0mEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_Tw_jcE0nEfCJQ8HsncGeQQ" name="newForm14" content="df3ae4cf-acf7-45e7-9c12-8209090a4b18" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_5HxCGU0mEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_LsdsUE0nEfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsUU0nEfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsUk0nEfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsU00nEfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsVE0nEfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsVU0nEfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsVk0nEfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsV00nEfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsWE0nEfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsWU0nEfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsWk0nEfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsW00nEfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsXE0nEfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_LsdsXU0nEfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsXk0nEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsX00nEfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsYE0nEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsYU0nEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsYk0nEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_LsdsY00nEfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_5HxCHE0mEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_Po4-QE0qEfCJQ8HsncGeQQ" name="Convergência das Avaliações" outgoing="_HN4kB00uEfCJQ8HsncGeQQ" incoming="_Po5lVE0qEfCJQ8HsncGeQQ _QNLXEE0qEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Po4-Qk0qEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Po4-QU0qEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Po4-Q00qEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_VvZssE0uEfCJQ8HsncGeQQ" name="Tem certificação de segurança/privacidade?" outgoing="_ZUgyME0uEfCJQ8HsncGeQQ _Ulzx8E0vEfCJQ8HsncGeQQ" incoming="_HN4kB00uEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_HN4kAU0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_HN4kAE0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_HN4kAk0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_dyqYgE0uEfCJQ8HsncGeQQ" name="Existem atrasos de entrega ou material não conforme?" outgoing="_gMHjME0uEfCJQ8HsncGeQQ _S1cnkE0vEfCJQ8HsncGeQQ" incoming="_ZUgyME0uEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZUgLIk0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZUgLIU0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ZUgLI00uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_gtntwE0uEfCJQ8HsncGeQQ" name="Políticas de segurança e proteção de dados cumpridas?" outgoing="_21-E9E0uEfCJQ8HsncGeQQ _56m6oE0uEfCJQ8HsncGeQQ" incoming="_gMHjME0uEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_gMG8Ik0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_gMG8IU0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_gMG8I00uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_yupDME0uEfCJQ8HsncGeQQ" name="Realizar auditoria/questionário de avaliação" outgoing="_cnESok0vEfCJQ8HsncGeQQ" incoming="_56m6oE0uEfCJQ8HsncGeQQ _S1cnkE0vEfCJQ8HsncGeQQ _Ulzx8E0vEfCJQ8HsncGeQQ" actor="__zGfsEvIEfCLgOL9T1jGqw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_qBj-Uk0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_qBj-UU0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_qBj-U00uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <data xmi:type="process:Data" xmi:id="_qYZFwE01EfCJQ8HsncGeQQ" name="auditoriaInput" dataType="_tdpK4TsGEfCUCLU1D69YIQ">
          <defaultValue xmi:type="expression:Expression" xmi:id="_qYZFwU01EfCJQ8HsncGeQQ" name="" content=""/>
        </data>
        <operations xmi:type="expression:Operation" xmi:id="_fXKXgE02EfCJQ8HsncGeQQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_fXKXgU02EfCJQ8HsncGeQQ" name="avaliacaoFornecedor" content="avaliacaoFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_VhVagE05EfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_fXKXgk02EfCJQ8HsncGeQQ" name="newScript()" content="def avaliacao = new com.company.model.AvaliacaoFornecedor()&#xD;&#xA;avaliacao.fornecedorId = avaliacaoFornecedorInput.fornecedorId&#xD;&#xA;avaliacao.dataAvaliacao = avaliacaoFornecedorInput.dataAuditoria&#xD;&#xA;avaliacao.descricaoNaoConformidades = avaliacaoFornecedorInput.checklistAuditoria&#xD;&#xA;avaliacao.observacoesAvaliacao = avaliacaoFornecedorInput.comentariosAuditoria&#xD;&#xA;avaliacao.documentosAnexados = avaliacaoFornecedorInput.documentosAnexados&#xD;&#xA;return avaliacao&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.AvaliacaoFornecedor">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_bnpRcE05EfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_fXKXg002EfCJQ8HsncGeQQ" type="ASSIGNMENT"/>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_qBj-VE0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_qBj-VU0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qBj-Vk0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_qBj-WE0uEfCJQ8HsncGeQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_qBj-V00uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_yupDOk0uEfCJQ8HsncGeQQ">
          <targetForm xmi:type="expression:Expression" xmi:id="_ty-g0E02EfCJQ8HsncGeQQ" name="newForm21" content="33dd681c-87c5-4515-9f37-c7225b979d3e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_yupDOU0uEfCJQ8HsncGeQQ">
          <inputs xmi:type="process:ContractInput" xmi:id="_XYEaAE02EfCJQ8HsncGeQQ" name="avaliacaoFornecedorInput" type="COMPLEX" dataReference="avaliacaoFornecedor" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaAU02EfCJQ8HsncGeQQ" name="fornecedorId" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaAk02EfCJQ8HsncGeQQ" name="dataAvaliacao" type="LOCALDATE" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaA002EfCJQ8HsncGeQQ" name="nivelServico" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaBE02EfCJQ8HsncGeQQ" name="avaliacaoIncidentes" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaBU02EfCJQ8HsncGeQQ" name="formacaoCertificacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaBk02EfCJQ8HsncGeQQ" name="naoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaB002EfCJQ8HsncGeQQ" name="descricaoNaoConformidades" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaCE02EfCJQ8HsncGeQQ" name="condicoesCredito" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaCU02EfCJQ8HsncGeQQ" name="condicoesFornecimento" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaCk02EfCJQ8HsncGeQQ" name="classificacaoDesempenho" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaC002EfCJQ8HsncGeQQ" name="observacoesAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaDE02EfCJQ8HsncGeQQ" name="responsavelAvaliacao" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_XYEaDU02EfCJQ8HsncGeQQ" name="numeroIncidentes" type="BOOLEAN" createMode="false"/>
          </inputs>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaDk02EfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.fornecedorId != null" errorMessage="fornecedorId is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaD002EfCJQ8HsncGeQQ" expression="!avaliacaoFornecedorInput?.fornecedorId || avaliacaoFornecedorInput?.fornecedorId.isLong()" errorMessage="A Long value is expected for AvaliacaoFornecedor.fornecedorId" name="type_long_avaliacaoFornecedorInput_fornecedorId">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaEE02EfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.dataAvaliacao != null" errorMessage="dataAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_dataAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaEU02EfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.nivelServico != null" errorMessage="nivelServico is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_nivelServico">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaEk02EfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.classificacaoDesempenho != null" errorMessage="classificacaoDesempenho is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_classificacaoDesempenho">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
          <constraints xmi:type="process:ContractConstraint" xmi:id="_XYEaE002EfCJQ8HsncGeQQ" expression="avaliacaoFornecedorInput?.responsavelAvaliacao != null" errorMessage="responsavelAvaliacao is mandatory for AvaliacaoFornecedor" name="mandatory_avaliacaoFornecedorInput_responsavelAvaliacao">
            <inputNames>avaliacaoFornecedorInput</inputNames>
          </constraints>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_yupDPE0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_21820E0uEfCJQ8HsncGeQQ" name="Processo Finalizado " incoming="_21-E9E0uEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_219d4U0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_219d4E0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_219d4k0uEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_cnDrkE0vEfCJQ8HsncGeQQ" name="Fim" incoming="_cnESok0vEfCJQ8HsncGeQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_cnDrkk0vEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_cnDrkU0vEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_cnDrk00vEfCJQ8HsncGeQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_t1ScoEuDEfCM-NwOUWra6Q" name="fornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.Fornecedor">
        <defaultValue xmi:type="expression:Expression" xmi:id="_t1ScoUuDEfCM-NwOUWra6Q" name="init_fornecedor()" content="def fornecedorVar = new com.company.model.Fornecedor()&#xD;&#xA;fornecedorVar.nome = fornecedorInput.nome&#xD;&#xA;fornecedorVar.nif = fornecedorInput.nif&#xD;&#xA;fornecedorVar.endereco = fornecedorInput.endereco&#xD;&#xA;fornecedorVar.localidade = fornecedorInput.localidade&#xD;&#xA;fornecedorVar.codigoPostal = fornecedorInput.codigoPostal&#xD;&#xA;fornecedorVar.distrito = fornecedorInput.distrito&#xD;&#xA;fornecedorVar.contactoEmail = fornecedorInput.contactoEmail&#xD;&#xA;fornecedorVar.contactoTelefone = fornecedorInput.contactoTelefone&#xD;&#xA;fornecedorVar.tipo = fornecedorInput.tipo&#xD;&#xA;fornecedorVar.status = fornecedorInput.status&#xD;&#xA;fornecedorVar.forneceuAntes = fornecedorInput.forneceuAntes&#xD;&#xA;return fornecedorVar&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Fornecedor">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_UaJy0EzzEfC0mryHjxjYFA" name="fornecedorInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yr_BoEuKEfCyX9uolcYbeQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yr_BoUuKEfCyX9uolcYbeQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_a4OK4EwhEfC7vJQ9JxI0Zw" documentation="Indica se as condições de fornecimento do fornecedor foram aprovadas nesta etapa de avaliação." name="condicoesFornecimentoAprovadas" dataType="_tdpK3DsGEfCUCLU1D69YIQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_a4OK4UwhEfC7vJQ9JxI0Zw" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_tdpKxDsGEfCUCLU1D69YIQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_muyYUExlEfC7vJQ9JxI0Zw" name="instanciarFornecedor" content="cc8fa7ba-4eb5-45a9-9061-cc4fca6152ae" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_tdpKxjsGEfCUCLU1D69YIQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_A5dVcExmEfC7vJQ9JxI0Zw" name="overviewFornecedor" content="32b580ba-9f44-4e43-8030-66ba409c48cc" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G-gq8DsJEfCUCLU1D69YIQ" target="_LEiO8EuNEfCyX9uolcYbeQ" source="_tdpKszsGEfCUCLU1D69YIQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G-gq8TsJEfCUCLU1D69YIQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_73mxwkuMEfCyX9uolcYbeQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g9TKUEzzEfC0mryHjxjYFA" name="Serviço" target="_NEm2sEz1EfCtoJWwOFxQ4w" source="_LEiO8EuNEfCyX9uolcYbeQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g9TKUUzzEfC0mryHjxjYFA"/>
        <condition xmi:type="expression:Expression" xmi:id="_g9TKUkzzEfC0mryHjxjYFA" name="newScript()" content="fornecedor.tipo == &quot;Serviço&quot;&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nkv_cEzzEfC0mryHjxjYFA" name="fornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.Fornecedor"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_o7MN80zzEfC0mryHjxjYFA" name="Produto " target="_w14lEE0eEfCJQ8HsncGeQQ" source="_LEiO8EuNEfCyX9uolcYbeQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_o7MN9EzzEfC0mryHjxjYFA"/>
        <condition xmi:type="expression:Expression" xmi:id="_o7MN9UzzEfC0mryHjxjYFA" name="newScript()" content="fornecedor.tipo == &quot;Produto&quot;&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tYNy4EzzEfC0mryHjxjYFA" name="fornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.Fornecedor"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GUKPEE0gEfCJQ8HsncGeQQ" target="_GtG6kE0gEfCJQ8HsncGeQQ" source="_NEm2sEz1EfCtoJWwOFxQ4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GUKPEU0gEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GUKPEk0gEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bKgWY00hEfCJQ8HsncGeQQ" target="_bXGA4E0hEfCJQ8HsncGeQQ" source="_w14lEE0eEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bKgWZE0hEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_bKgWZU0hEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NUi2sE0iEfCJQ8HsncGeQQ" target="_LVJx0E0iEfCJQ8HsncGeQQ" source="_bXGA4E0hEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NUi2sU0iEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_NUi2sk0iEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZVRdo00iEfCJQ8HsncGeQQ" target="_ZjQ2UE0iEfCJQ8HsncGeQQ" source="_GtG6kE0gEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZVRdpE0iEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZVRdpU0iEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cqAvYE0jEfCJQ8HsncGeQQ" target="_c4Hc0E0jEfCJQ8HsncGeQQ" source="_ZjQ2UE0iEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cqAvYU0jEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_cqAvYk0jEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_45VkgE0mEfCJQ8HsncGeQQ" target="_5HxCEE0mEfCJQ8HsncGeQQ" source="_c4Hc0E0jEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_45VkgU0mEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_45Vkgk0mEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Po5lVE0qEfCJQ8HsncGeQQ" target="_Po4-QE0qEfCJQ8HsncGeQQ" source="_5HxCEE0mEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Po5lVU0qEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Po5lVk0qEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QNLXEE0qEfCJQ8HsncGeQQ" target="_Po4-QE0qEfCJQ8HsncGeQQ" source="_LVJx0E0iEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QNLXEU0qEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QNLXEk0qEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HN4kB00uEfCJQ8HsncGeQQ" target="_VvZssE0uEfCJQ8HsncGeQQ" source="_Po4-QE0qEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HN4kCE0uEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HN4kCU0uEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZUgyME0uEfCJQ8HsncGeQQ" name="Sim" target="_dyqYgE0uEfCJQ8HsncGeQQ" source="_VvZssE0uEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZUgyMU0uEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZUgyMk0uEfCJQ8HsncGeQQ" name="newScript()" content="avaliacaoFornecedor.formacaoCertificacao != null &amp;&amp; !avaliacaoFornecedor.formacaoCertificacao.isEmpty()&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_PDp0IE0zEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gMHjME0uEfCJQ8HsncGeQQ" name="Não" target="_gtntwE0uEfCJQ8HsncGeQQ" source="_dyqYgE0uEfCJQ8HsncGeQQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gMHjMU0uEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gMHjMk0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_21-E9E0uEfCJQ8HsncGeQQ" name="Sim" target="_21820E0uEfCJQ8HsncGeQQ" source="_gtntwE0uEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_21-E9U0uEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_21-E9k0uEfCJQ8HsncGeQQ" name="newScript()" content="avaliacaoFornecedor.observacoesAvaliacao != null &amp;&amp; avaliacaoFornecedor.observacoesAvaliacao.contains(&quot;cumpre política&quot;)&#xD;&#xA;&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="__c_9cE00EfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_56m6oE0uEfCJQ8HsncGeQQ" name="Não" target="_yupDME0uEfCJQ8HsncGeQQ" source="_gtntwE0uEfCJQ8HsncGeQQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_56m6oU0uEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_56m6ok0uEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S1cnkE0vEfCJQ8HsncGeQQ" name="Sim" target="_yupDME0uEfCJQ8HsncGeQQ" source="_dyqYgE0uEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S1cnkU0vEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_S1cnkk0vEfCJQ8HsncGeQQ" name="newScript()" content="(avaliacaoFornecedor.avaliacaoIncidentes != null &amp;&amp; !avaliacaoFornecedor.avaliacaoIncidentes.isEmpty()) ||&#xD;&#xA;(avaliacaoFornecedor.naoConformidades != null &amp;&amp; !avaliacaoFornecedor.naoConformidades.isEmpty())&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RldCgE0zEfCJQ8HsncGeQQ" name="avaliacaoFornecedor" dataType="_tdpK5DsGEfCUCLU1D69YIQ" className="com.company.model.AvaliacaoFornecedor"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ulzx8E0vEfCJQ8HsncGeQQ" name="Não" target="_yupDME0uEfCJQ8HsncGeQQ" source="_VvZssE0uEfCJQ8HsncGeQQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ulzx8U0vEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ulzx8k0vEfCJQ8HsncGeQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cnESok0vEfCJQ8HsncGeQQ" target="_cnDrkE0vEfCJQ8HsncGeQQ" source="_yupDME0uEfCJQ8HsncGeQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cnESo00vEfCJQ8HsncGeQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_cnESpE0vEfCJQ8HsncGeQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_KJVQIEt7EfCM-NwOUWra6Q" name="Fornecedor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="__zGfsEvIEfCLgOL9T1jGqw" name="Gestor Qualidade"/>
      <actors xmi:type="process:Actor" xmi:id="_oyfOUEvJEfCLgOL9T1jGqw" name="Gestor Crédito"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_NDUi4ExpEfC7vJQ9JxI0Zw" name="Production" version="8" username="william.jobs">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_NDVJ8ExpEfC7vJQ9JxI0Zw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVJ8UxpEfC7vJQ9JxI0Zw" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVJ8kxpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVJ80xpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVJ9ExpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVJ9UxpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVJ9kxpEfC7vJQ9JxI0Zw" name="Fornecedor">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVJ90xpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVJ-ExpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVJ-UxpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVJ-kxpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVJ-0xpEfC7vJQ9JxI0Zw" name="Aprovisionamento">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVJ_ExpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVJ_UxpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVJ_kxpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVJ_0xpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVKAExpEfC7vJQ9JxI0Zw" name="Administração">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVKAUxpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVKAkxpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVKA0xpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVKBExpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVKBUxpEfC7vJQ9JxI0Zw" name="Diretor">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVKBkxpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVKB0xpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVKCExpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVKCUxpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVKCkxpEfC7vJQ9JxI0Zw" name="Gestor Qualidade">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVKC0xpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVKDExpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVKDUxpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVKDkxpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVKD0xpEfC7vJQ9JxI0Zw" name="Recursos Humanos">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVKEExpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVKEUxpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVKEkxpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVKE0xpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_NDVKFExpEfC7vJQ9JxI0Zw" name="Gestor Crédito">
            <groups xmi:type="actormapping:Groups" xmi:id="_NDVKFUxpEfC7vJQ9JxI0Zw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_NDVKFkxpEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_NDVKF0xpEfC7vJQ9JxI0Zw"/>
            <users xmi:type="actormapping:Users" xmi:id="_NDVKGExpEfC7vJQ9JxI0Zw"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_NDUi4UxpEfC7vJQ9JxI0Zw" type="ACTOR_FILTER" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0" implementationId="bonita-actorfilter-initiator-impl" implementationVersion="1.0.0"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_NDUi4kxpEfC7vJQ9JxI0Zw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_NDUi40xpEfC7vJQ9JxI0Zw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_NDUi5ExpEfC7vJQ9JxI0Zw" id="ACTOR_FILTER">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_NDUi5UxpEfC7vJQ9JxI0Zw" id="bonita-actorfilter-initiator-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_NDUi5kxpEfC7vJQ9JxI0Zw" key="bonita-actorfilter-initiator-impl -- 1.0.0" value="bonita-actorfilter-initiator-1.0.0.jar" type="ACTOR_FILTER"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_NDUi50xpEfC7vJQ9JxI0Zw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_NDUi6ExpEfC7vJQ9JxI0Zw" id="GROOVY_SCRIPT"/>
      </configurations>
      <configurations xmi:type="configuration:Configuration" xmi:id="_3tm3oExqEfC7vJQ9JxI0Zw" name="Qualification" version="8" username="william.jobs">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_3tm3qUxqEfC7vJQ9JxI0Zw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tm3qkxqEfC7vJQ9JxI0Zw" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tm3q0xqEfC7vJQ9JxI0Zw">
              <group>/Colaboradores</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tm3rExqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tm3rUxqEfC7vJQ9JxI0Zw">
              <role>Colaborador</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tm3rkxqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tm3r0xqEfC7vJQ9JxI0Zw" name="Fornecedor">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tm3sExqEfC7vJQ9JxI0Zw">
              <group>/Fornecedores</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tm3sUxqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tm3skxqEfC7vJQ9JxI0Zw">
              <role>Fornecedor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tm3s0xqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tm3tExqEfC7vJQ9JxI0Zw" name="Aprovisionamento">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tm3tUxqEfC7vJQ9JxI0Zw">
              <group>/Aprovisionamento</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tm3tkxqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tm3t0xqEfC7vJQ9JxI0Zw">
              <role>Gestor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tm3uExqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tm3uUxqEfC7vJQ9JxI0Zw" name="Administração">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tnesExqEfC7vJQ9JxI0Zw">
              <group>/Administração</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tnesUxqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tneskxqEfC7vJQ9JxI0Zw">
              <role>Diretor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tnes0xqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tnetExqEfC7vJQ9JxI0Zw" name="Diretor">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tnetUxqEfC7vJQ9JxI0Zw">
              <group>/Direção</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tnetkxqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tnet0xqEfC7vJQ9JxI0Zw">
              <role>Diretor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tneuExqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tneuUxqEfC7vJQ9JxI0Zw" name="Gestor Qualidade">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tneukxqEfC7vJQ9JxI0Zw">
              <group>/Qualidade</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tneu0xqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tnevExqEfC7vJQ9JxI0Zw">
              <role>Gestor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tnevUxqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tnevkxqEfC7vJQ9JxI0Zw" name="Recursos Humanos">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tnev0xqEfC7vJQ9JxI0Zw">
              <group>/RecursosHumanos</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tnewExqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tnewUxqEfC7vJQ9JxI0Zw">
              <role>RH</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tnewkxqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_3tnew0xqEfC7vJQ9JxI0Zw" name="Gestor Crédito">
            <groups xmi:type="actormapping:Groups" xmi:id="_3tnexExqEfC7vJQ9JxI0Zw">
              <group>/Financeiro</group>
            </groups>
            <memberships xmi:type="actormapping:Membership" xmi:id="_3tnexUxqEfC7vJQ9JxI0Zw"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_3tnexkxqEfC7vJQ9JxI0Zw">
              <role>Gestor</role>
            </roles>
            <users xmi:type="actormapping:Users" xmi:id="_3tnex0xqEfC7vJQ9JxI0Zw"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_3tm3oUxqEfC7vJQ9JxI0Zw" type="ACTOR_FILTER" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0" implementationId="bonita-actorfilter-initiator-impl" implementationVersion="1.0.0"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3tm3okxqEfC7vJQ9JxI0Zw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3tm3o0xqEfC7vJQ9JxI0Zw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3tm3pExqEfC7vJQ9JxI0Zw" id="ACTOR_FILTER">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_3tm3pUxqEfC7vJQ9JxI0Zw" id="bonita-actorfilter-initiator-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_3tm3pkxqEfC7vJQ9JxI0Zw" key="bonita-actorfilter-initiator-impl -- 1.0.0" value="bonita-actorfilter-initiator-1.0.0.jar" type="ACTOR_FILTER"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3tm3p0xqEfC7vJQ9JxI0Zw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_3tm3qExqEfC7vJQ9JxI0Zw" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_tdpKzDsGEfCUCLU1D69YIQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_XdMHUEuFEfCM-NwOUWra6Q" name="fornecedorInput" type="COMPLEX" dataReference="fornecedor">
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHUUuFEfCM-NwOUWra6Q" name="nome"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHUkuFEfCM-NwOUWra6Q" name="nif"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHU0uFEfCM-NwOUWra6Q" name="endereco"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHVEuFEfCM-NwOUWra6Q" name="localidade"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHVUuFEfCM-NwOUWra6Q" name="codigoPostal"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHVkuFEfCM-NwOUWra6Q" name="distrito"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHV0uFEfCM-NwOUWra6Q" name="contactoEmail"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHWEuFEfCM-NwOUWra6Q" name="contactoTelefone"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHWUuFEfCM-NwOUWra6Q" name="tipo"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHWkuFEfCM-NwOUWra6Q" name="status"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_XdMHW0uFEfCM-NwOUWra6Q" name="forneceuAntes" type="BOOLEAN"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_XdMHXEuFEfCM-NwOUWra6Q" expression="fornecedorInput?.nome != null" errorMessage="nome is mandatory for Fornecedor" name="mandatory_fornecedorInput_nome">
          <inputNames>fornecedorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_XdMHXUuFEfCM-NwOUWra6Q" expression="fornecedorInput?.nif != null" errorMessage="nif is mandatory for Fornecedor" name="mandatory_fornecedorInput_nif">
          <inputNames>fornecedorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_XdMHXkuFEfCM-NwOUWra6Q" expression="fornecedorInput?.contactoEmail != null" errorMessage="contactoEmail is mandatory for Fornecedor" name="mandatory_fornecedorInput_contactoEmail">
          <inputNames>fornecedorInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_XdMHX0uFEfCM-NwOUWra6Q" expression="fornecedorInput?.tipo != null" errorMessage="tipo is mandatory for Fornecedor" name="mandatory_fornecedorInput_tipo">
          <inputNames>fornecedorInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tdpKzTsGEfCUCLU1D69YIQ">
        <name xmi:type="expression:Expression" xmi:id="_tdpKzjsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tdpKzzsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tdpK0DsGEfCUCLU1D69YIQ">
        <name xmi:type="expression:Expression" xmi:id="_tdpK0TsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tdpK0jsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tdpK0zsGEfCUCLU1D69YIQ">
        <name xmi:type="expression:Expression" xmi:id="_tdpK1DsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tdpK1TsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tdpK1jsGEfCUCLU1D69YIQ">
        <name xmi:type="expression:Expression" xmi:id="_tdpK1zsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tdpK2DsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tdpK2TsGEfCUCLU1D69YIQ">
        <name xmi:type="expression:Expression" xmi:id="_tdpK2jsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tdpK2zsGEfCUCLU1D69YIQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_tdpK3DsGEfCUCLU1D69YIQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_tdpK3TsGEfCUCLU1D69YIQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_tdpK3jsGEfCUCLU1D69YIQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_tdpK3zsGEfCUCLU1D69YIQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_tdpK4DsGEfCUCLU1D69YIQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_tdpK4TsGEfCUCLU1D69YIQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_tdpK4jsGEfCUCLU1D69YIQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_tdpK4zsGEfCUCLU1D69YIQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_tdpK5DsGEfCUCLU1D69YIQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_tdpK5TsGEfCUCLU1D69YIQ" type="Process" element="_tdpKsDsGEfCUCLU1D69YIQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_tdpK5jsGEfCUCLU1D69YIQ" type="2007" element="_tdpKsTsGEfCUCLU1D69YIQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_tdpK5zsGEfCUCLU1D69YIQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_tdpK6DsGEfCUCLU1D69YIQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_tdpK7zsGEfCUCLU1D69YIQ" type="3002" element="_tdpKszsGEfCUCLU1D69YIQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_tdpK8DsGEfCUCLU1D69YIQ" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_tdpK8TsGEfCUCLU1D69YIQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tdpK8jsGEfCUCLU1D69YIQ" x="49" y="140"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_LEi2A0uNEfCyX9uolcYbeQ" type="3008" element="_LEiO8EuNEfCyX9uolcYbeQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_LEi2BUuNEfCyX9uolcYbeQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_LEi2BkuNEfCyX9uolcYbeQ" x="109" y="-23"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LEi2BEuNEfCyX9uolcYbeQ" x="189" y="141" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_NEwAoEz1EfCtoJWwOFxQ4w" type="3005" element="_NEm2sEz1EfCtoJWwOFxQ4w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_NEwnsEz1EfCtoJWwOFxQ4w" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NEwAoUz1EfCtoJWwOFxQ4w" x="314" y="27" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_w2BH8E0eEfCJQ8HsncGeQQ" type="3005" element="_w14lEE0eEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_w2BH8k0eEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w2BH8U0eEfCJQ8HsncGeQQ" x="318" y="283" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_GtHhoE0gEfCJQ8HsncGeQQ" type="3005" element="_GtG6kE0gEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_GtHhok0gEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GtHhoU0gEfCJQ8HsncGeQQ" x="483" y="27" width="122" height="61"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_bXGA7U0hEfCJQ8HsncGeQQ" type="3005" element="_bXGA4E0hEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_bXGA700hEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bXGA7k0hEfCJQ8HsncGeQQ" x="497" y="280" width="126" height="63"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_LVKY4E0iEfCJQ8HsncGeQQ" type="3005" element="_LVJx0E0iEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_LVKY4U0iEfCJQ8HsncGeQQ" type="5005" element="_LVJx0E0iEfCJQ8HsncGeQQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LVKY4k0iEfCJQ8HsncGeQQ" x="654" y="282" width="122" height="61"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ZjRdYE0iEfCJQ8HsncGeQQ" type="3005" element="_ZjQ2UE0iEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_ZjRdYk0iEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZjRdYU0iEfCJQ8HsncGeQQ" x="653" y="22" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_c4ID4E0jEfCJQ8HsncGeQQ" type="3005" element="_c4Hc0E0jEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_c4ID4k0jEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c4ID4U0jEfCJQ8HsncGeQQ" x="825" y="20" width="134" height="67"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_5HxCHU0mEfCJQ8HsncGeQQ" type="3005" element="_5HxCEE0mEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_5HxpIE0mEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5HxCHk0mEfCJQ8HsncGeQQ" x="996" y="32" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Po5lUE0qEfCJQ8HsncGeQQ" type="3009" element="_Po4-QE0qEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Po5lUk0qEfCJQ8HsncGeQQ" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Po5lU00qEfCJQ8HsncGeQQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Po5lUU0qEfCJQ8HsncGeQQ" x="920" y="282"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_VvaTw00uEfCJQ8HsncGeQQ" type="3008" element="_VvZssE0uEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_VvaTxU0uEfCJQ8HsncGeQQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_VvaTxk0uEfCJQ8HsncGeQQ" x="-1" y="-63"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VvaTxE0uEfCJQ8HsncGeQQ" x="1167" y="282" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_dyqYhE0uEfCJQ8HsncGeQQ" type="3008" element="_dyqYgE0uEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_dyqYhk0uEfCJQ8HsncGeQQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_dyqYh00uEfCJQ8HsncGeQQ" x="13" y="-67"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dyqYhU0uEfCJQ8HsncGeQQ" x="1561" y="286" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_gtoU000uEfCJQ8HsncGeQQ" type="3008" element="_gtntwE0uEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_gtoU1U0uEfCJQ8HsncGeQQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_gtoU1k0uEfCJQ8HsncGeQQ" x="1" y="-67"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gtoU1E0uEfCJQ8HsncGeQQ" x="1905" y="286" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_yupDPU0uEfCJQ8HsncGeQQ" type="3005" element="_yupDME0uEfCJQ8HsncGeQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_yupDP00uEfCJQ8HsncGeQQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yupDPk0uEfCJQ8HsncGeQQ" x="1490" y="388" width="153" height="76"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_21-E8E0uEfCJQ8HsncGeQQ" type="3062" element="_21820E0uEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_21-E8k0uEfCJQ8HsncGeQQ" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_21-E800uEfCJQ8HsncGeQQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_21-E8U0uEfCJQ8HsncGeQQ" x="2136" y="291"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_cnDrlE0vEfCJQ8HsncGeQQ" type="3003" element="_cnDrkE0vEfCJQ8HsncGeQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_cnESoE0vEfCJQ8HsncGeQQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_cnESoU0vEfCJQ8HsncGeQQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cnDrlU0vEfCJQ8HsncGeQQ" x="1552" y="516"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_tdpK-DsGEfCUCLU1D69YIQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_tdpK-TsGEfCUCLU1D69YIQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_tdpK-jsGEfCUCLU1D69YIQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_tdpK-zsGEfCUCLU1D69YIQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tdpK_DsGEfCUCLU1D69YIQ" width="2260" height="587"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_tdpK_TsGEfCUCLU1D69YIQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_G-hSADsJEfCUCLU1D69YIQ" type="4001" element="_G-gq8DsJEfCUCLU1D69YIQ" source="_tdpK7zsGEfCUCLU1D69YIQ" target="_LEi2A0uNEfCyX9uolcYbeQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_G-hSAzsJEfCUCLU1D69YIQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G-hSBDsJEfCUCLU1D69YIQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G-hSATsJEfCUCLU1D69YIQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G-hSAjsJEfCUCLU1D69YIQ" points="[-4, -1, -80, -12]$[72, -6, -4, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_G-jHMDsJEfCUCLU1D69YIQ" id="(1.0,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g9TKU0zzEfC0mryHjxjYFA" type="4001" element="_g9TKUEzzEfC0mryHjxjYFA" source="_LEi2A0uNEfCyX9uolcYbeQ" target="_NEwAoEz1EfCtoJWwOFxQ4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g9TKVkzzEfC0mryHjxjYFA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g9TKV0zzEfC0mryHjxjYFA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g9TKVEzzEfC0mryHjxjYFA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g9TKVUzzEfC0mryHjxjYFA" points="[-2, -19, -157, 83]$[-2, -104, -157, -2]$[105, -104, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_o7MN9kzzEfC0mryHjxjYFA" type="4001" element="_o7MN80zzEfC0mryHjxjYFA" source="_LEi2A0uNEfCyX9uolcYbeQ" target="_w2BH8E0eEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_o7MN-UzzEfC0mryHjxjYFA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_o7MN-kzzEfC0mryHjxjYFA" x="-16" y="-32"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_o7MN90zzEfC0mryHjxjYFA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_o7MN-EzzEfC0mryHjxjYFA" points="[-2, 19, -160, -134]$[-2, 156, -160, 3]$[108, 156, -50, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GUK2IE0gEfCJQ8HsncGeQQ" type="4001" element="_GUKPEE0gEfCJQ8HsncGeQQ" source="_NEwAoEz1EfCtoJWwOFxQ4w" target="_GtHhoE0gEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GUK2I00gEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GUK2JE0gEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GUK2IU0gEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GUK2Ik0gEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bKg9cE0hEfCJQ8HsncGeQQ" type="4001" element="_bKgWY00hEfCJQ8HsncGeQQ" source="_w2BH8E0eEfCJQ8HsncGeQQ" target="_bXGA7U0hEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bKg9c00hEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bKg9dE0hEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bKg9cU0hEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bKg9ck0hEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NUjdwE0iEfCJQ8HsncGeQQ" type="4001" element="_NUi2sE0iEfCJQ8HsncGeQQ" source="_bXGA7U0hEfCJQ8HsncGeQQ" target="_LVKY4E0iEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NUjdw00iEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NUjdxE0iEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NUjdwU0iEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NUjdwk0iEfCJQ8HsncGeQQ" points="[0, 3, -41, 0]$[31, 2, -10, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NUkr4E0iEfCJQ8HsncGeQQ" id="(1.0,0.3968253968253968)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NUkr4U0iEfCJQ8HsncGeQQ" id="(0.08196721311475409,0.4262295081967213)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZVSEsE0iEfCJQ8HsncGeQQ" type="4001" element="_ZVRdo00iEfCJQ8HsncGeQQ" source="_GtHhoE0gEfCJQ8HsncGeQQ" target="_ZjRdYE0iEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZVSEs00iEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZVSEtE0iEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZVSEsU0iEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZVSEsk0iEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cqAvY00jEfCJQ8HsncGeQQ" type="4001" element="_cqAvYE0jEfCJQ8HsncGeQQ" source="_ZjRdYE0iEfCJQ8HsncGeQQ" target="_c4ID4E0jEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cqAvZk0jEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cqAvZ00jEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cqAvZE0jEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cqAvZU0jEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_45Vkg00mEfCJQ8HsncGeQQ" type="4001" element="_45VkgE0mEfCJQ8HsncGeQQ" source="_c4ID4E0jEfCJQ8HsncGeQQ" target="_5HxCHU0mEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_45Vkhk0mEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_45Vkh00mEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_45VkhE0mEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_45VkhU0mEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Po5lV00qEfCJQ8HsncGeQQ" type="4001" element="_Po5lVE0qEfCJQ8HsncGeQQ" source="_5HxCHU0mEfCJQ8HsncGeQQ" target="_Po5lUE0qEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Po5lWk0qEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Po5lW00qEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Po5lWE0qEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Po5lWU0qEfCJQ8HsncGeQQ" points="[-3, 30, 112, -211]$[-3, 121, 112, -120]$[-108, 121, 7, -120]$[-108, 226, 7, -15]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OFkNgE0uEfCJQ8HsncGeQQ" id="(0.2558139534883721,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QNL-IE0qEfCJQ8HsncGeQQ" type="4001" element="_QNLXEE0qEfCJQ8HsncGeQQ" source="_LVKY4E0iEfCJQ8HsncGeQQ" target="_Po5lUE0qEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QNL-I00qEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QNL-JE0qEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QNL-IU0qEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QNL-Ik0qEfCJQ8HsncGeQQ" points="[0, 0, -260, 41]$[257, -42, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QNMlME0qEfCJQ8HsncGeQQ" id="(1.0,0.4098360655737705)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_QNMlMU0qEfCJQ8HsncGeQQ" id="(0.11627906976744186,0.4418604651162791)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HN5LEE0uEfCJQ8HsncGeQQ" type="4001" element="_HN4kB00uEfCJQ8HsncGeQQ" source="_Po5lUE0qEfCJQ8HsncGeQQ" target="_VvaTw00uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HN5LE00uEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HN5LFE0uEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HN5LEU0uEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HN5LEk0uEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZUgyM00uEfCJQ8HsncGeQQ" type="4001" element="_ZUgyME0uEfCJQ8HsncGeQQ" source="_VvaTw00uEfCJQ8HsncGeQQ" target="_dyqYhE0uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZUgyNk0uEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZUgyN00uEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZUgyNE0uEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZUgyNU0uEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gMHjM00uEfCJQ8HsncGeQQ" type="4001" element="_gMHjME0uEfCJQ8HsncGeQQ" source="_dyqYhE0uEfCJQ8HsncGeQQ" target="_gtoU000uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gMHjNk0uEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gMHjN00uEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gMHjNE0uEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gMHjNU0uEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_21-E900uEfCJQ8HsncGeQQ" type="4001" element="_21-E9E0uEfCJQ8HsncGeQQ" source="_gtoU000uEfCJQ8HsncGeQQ" target="_21-E8E0uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_21-E-k0uEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_21-E-00uEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_21-E-E0uEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_21-E-U0uEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_56tBQE0uEfCJQ8HsncGeQQ" type="4001" element="_56m6oE0uEfCJQ8HsncGeQQ" source="_gtoU000uEfCJQ8HsncGeQQ" target="_yupDPU0uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_56toUE0uEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_56toUU0uEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_56tBQU0uEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_56tBQk0uEfCJQ8HsncGeQQ" points="[-24, 11, 358, -100]$[-24, 109, 358, -2]$[-305, 109, 77, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_56uPYE0uEfCJQ8HsncGeQQ" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S1jVQE0vEfCJQ8HsncGeQQ" type="4001" element="_S1cnkE0vEfCJQ8HsncGeQQ" source="_dyqYhE0uEfCJQ8HsncGeQQ" target="_yupDPU0uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S1jVQ00vEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S1jVRE0vEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S1jVQU0vEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S1jVQk0vEfCJQ8HsncGeQQ" points="[-18, -2, 6, -54]$[-22, 44, 2, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S1j8UE0vEfCJQ8HsncGeQQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S1j8UU0vEfCJQ8HsncGeQQ" id="(0.5359477124183006,0.13157894736842105)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ul6foE0vEfCJQ8HsncGeQQ" type="4001" element="_Ulzx8E0vEfCJQ8HsncGeQQ" source="_VvaTw00uEfCJQ8HsncGeQQ" target="_yupDPU0uEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ul7GsE0vEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ul7GsU0vEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ul6foU0vEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ul6fok0vEfCJQ8HsncGeQQ" points="[-24, 3, -321, -113]$[-24, 109, -321, -7]$[280, 109, -17, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ul7twE0vEfCJQ8HsncGeQQ" id="(1.0,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ul7twU0vEfCJQ8HsncGeQQ" id="(0.1111111111111111,0.618421052631579)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cnESpU0vEfCJQ8HsncGeQQ" type="4001" element="_cnESok0vEfCJQ8HsncGeQQ" source="_yupDPU0uEfCJQ8HsncGeQQ" target="_cnDrlE0vEfCJQ8HsncGeQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cnESqE0vEfCJQ8HsncGeQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cnESqU0vEfCJQ8HsncGeQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cnESpk0vEfCJQ8HsncGeQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cnESp00vEfCJQ8HsncGeQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
